### ISSUE TITLE
stax info command

### ISSUE THREAD

**Issue by phstc** [rlister/stax#18]
It would be handy having a `stax info` command, similar to [`serverless info`](https://serverless.com/framework/docs/providers/aws/cli-reference/info/). 

This command could list all stacks defined in the `Stackfile`, tell if they `exist` or not, list outputs, list lambdas and APIGW endpoints etc.

### Suggestion for `stax info` v1:

- list all stacks defined in `Stackfile` and tell if they exist or not

### v2

- list outputs

### v3 

- list endpoints 

---

TBH v1 is good enough for my use case, I just want a quick overview on "what's going on", other suggestion are just "cool" stuff.

**Comment by rlister** [comment]
@phstc In general this is antithetical to the `stax` approach, which is not to limit to a bunch of highly-specific assumptions about what you're running. But we already have most of this info covered for you using mixins. Details to follow for v1,2,3.

**Comment by rlister** [comment]
Moving discussion of specifics to https://github.com/woodmont/capital/issues/723

**Comment by phstc** [comment]
@rlister stax does not need to do assumptions, the info should be based on the resources defined in the stacks `resource :mytable, 'AWS::DynamoDB::Table'`. 

If there's an `AWS::ApiGateway::Method` resource in a stack, it has an APIGW EP, if there's a `AWS::DynamoDB::Table`, there's a DDB table, therefore we can show its ARN.

**Comment by rlister** [comment]
@phstc Sorry, I don't understand. What's DynamoDB got to do with APIGW?

**Comment by phstc** [comment]
@rlister they are not related, I was just giving an example that the `info` command could list stacks  and for each stack show some info about its resources - without making any assumption, just using whatever is defined as a resource. If there's a stack called `my-stack` and it has resources `AWS::DynamoDB::Table`, it could show them.

For v1 of the `info` it could list APIGW endpoints, DynamoDB tables, outputs and exports - something like that.

**Comment by rlister** [comment]
@phstc OK, I see. We already have this concept in several app stacks with the `stat` task. It's just not been formalized as a standard `stax` thing yet. But I'm now motivated to do that because it is very useful. I just have to figure out some issues with Thor multiple-invokes :-)

**Comment by rlister** [comment]
@phstc This is now implemented in the latest release. Mixins can now define a list of tasks to be included in `info` listing, using the `stax_info` class method. Example:

https://github.com/rlister/stax/blob/master/lib/stax/mixin/apigw.rb#L13

Any given stack will now have an automatic `info` task, which will call this list for any `include`d mixins (in the order they were included).

Mixins with info tasks defined so far:

- alb
- apigw
- asg
- codebuild
- codepipeline
- dynamodb
- ecs
- elb
- lambda

**Comment by phstc** [comment]
@rlister nice, it worked great. How about a generic one "stax info` that lists that info for every stack defined in the Stackfile?

**Comment by rlister** [comment]
@phstc Would be easy to implement, but I think I'd rather not pollute the namespace. I can't see it being useful: way too much info to read, and generally one is only interested in a single stack at a time.

**Comment by phstc** [comment]
@rlister it is more like to see what's going on when I jump in an `ops` folder. But I guess `stax ls` already does that.
