### ISSUE TITLE
stax version

### ISSUE THREAD

**Issue by phstc** [rlister/stax#19]
`stax version` is currently broken:

> NameError: uninitialized constant Stax::Cli::VERSION

I faced that error while following the [installation instructions](https://github.com/rlister/stax#installation).

![image](https://user-images.githubusercontent.com/105652/40787922-c4f76cd0-64bc-11e8-80a1-594d40da5288.png)

**Comment by rlister** [comment]
Fixed by https://github.com/rlister/stax/commit/d70b204363adf023ba6c7525e60d4adf81875561

```
$ bundle exec stax version
0.0.6
```
