### ISSUE TITLE
RuntimeError: Expected a value or block when setting property DocileUndoFallback

### ISSUE THREAD

**Issue by phstc** [rlister/stax#21]
stax (cfer) depends on `gem 'docile', '1.2.0'` for proper working, if I use the latest it raises:

> RuntimeError: Expected a value or block when setting property DocileUndoFallback

Until cfer fixes it, it is probably worth to lock the `docile` version in stax [here](https://github.com/rlister/stax/blob/master/stax.gemspec#L26).

**Comment by rlister** [comment]
Fixed by https://github.com/rlister/stax/commit/f6ac3ed5f53f70ab53b3cc72d5e5a2f9e69eb8f7
