### ISSUE TITLE
stax up without a created stack fails silently

### ISSUE THREAD

**Issue by phstc** [rlister/stax#26]
If you `stax up` in a "stack" that wasn't created yet, it does not show any error message asking to create the stack first.

Maybe another option, would `stax deploy`, similar to `serverless deploy`, which creates or updates automatically, so we don't need to pick one or the other when we just want to get the changes out.

**Comment by phstc** [comment]
`stax deploy` is probably going to be useful when `stax create` fails `ROLLBACK` as well, since you can't use `stax create` again, you need to `stax update`, even if the creation has "failed". If we can use `stax deploy` all the time (create or update), we don't need to decide in between `create` or `update`.

**Comment by rlister** [comment]
1. I agree `stax update` should not be silent here.

2. The lack of `stax deploy` is a very conscious design decision. In Ops it is critical you are aware of what you are doing at all times. If I think a stack does not exist, and go to update, then the _actual_ existence of that stack should stop my operation and ask me to think carefully about what I am doing. It is important to be explicit about whether I am actually _creating_ new things, or _updating_ existing ones.

**Comment by rlister** [comment]
Fixed by https://github.com/rlister/stax/commit/38409df435a5b6235f16714a8680c669b47e12c3

Given some missing stacks:

```
$ stax ls
stax-master-vpc      -                        
stax-master-example  2018-06-08 14:23:35 UTC  CREATE_COMPLETE  example stack
stax-master-app      -
```

`update` now mentions they don't exist:

```
$ stax update
stax-master-vpc does not exist
Update stax-master-example? n
stax-master-app does not exist
```

**Comment by phstc** [comment]
2. I agree, but stax prompts already if you want to create etc, so it is just shortcut, it isn't going to do anything magical, since it prompts. I

**Comment by phstc** [comment]
`stax deploy` if stack exists, updates, If don't, prompts to create y/n. Nothing magical ✨, just shortcuts.

**Comment by rlister** [comment]
@phstc _thinks_ ...

I dislike `deploy` as a command because it implies deploying code specifically, rather than the infrastructure operation of bringing up a stack.

How about a compromise:

1. `stax up` will update if exists, or prompt to create if it doesn't.

2. `stax create` will still stop if stack exists. This is the most critical scenario: I thought I was making a new stack, but one already exists. There is a good chance I am on the wrong account or branch, or am confused about something. I need to stop and think before potentially breaking something.

**Comment by phstc** [comment]
@rlister Besides Serverless, [I think CF uses deploy as well](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html), which apparently works for update or create ❤️ 

> To update a stack, specify the name of an existing stack. To create a new stack, specify a new stack name.

**Comment by rlister** [comment]
@phstc That actually runs a changeset instead of update.

I disapprove, but will consider the most appropriate course of action 🤔

**Comment by phstc** [comment]
![](https://media.giphy.com/media/lXiRKeGZeOyEpRHkk/giphy.gif)
